baseURL = 'https://borocode.github.io/'
DefaultContentLanguage = "en"
languageCode = "en"
title = 'blog'
theme = "sk3"
copyright = "kekw"
summaryLength = 20
enableGitInfo          = true
enableInlineShortcodes = true
pagerSize              = 250
relativeURLs           = true


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 15

  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats/"
    weight = 5

      [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40

     [[menu.main]]
    identifier = "Netflix"
    name = "Netflix Viewing History"
    url = "/Netflix-Viewing-History/"
    weight = 50
    
[Params]
enableExternalSvg    = true
enableInfoBox        = true
enableListLastModify = false
enableOpenToc        = true
enableUserCanonical  = false
favicon              = "/favicon.ico"
mainSections         = "posts"
startdate            = "2022-08-13"
pagewidth            = "1680px"
enableTwitterCard     =   "true"
enableOpenGraph = "true"


	[Params.card]
	date    = true
	summary = true
   width = "100%"

   [Params.color]
   border = "#39ff14"
   link = "white"
   bg = "black"
   text = "#dddddd"
   
	[Params.sociallink]
  youtubeuser    = "rishard"
	github         = "borocode"
	rss            = true
  discord = "QRuHnxQWb4"
  twitch = "borokhela"
  flickr = "rishadphoto"
  instagram = "boroghor"
  facebook = "rishadh"
	